<?php /* @var $this Zend_View */ ?>

    <div class="row">
        <div class="col-md-12">
            Header!
        </div>
    </div>

<?php if ($this->query instanceof \Xend\WordPress\Query\QueryInterface) : ?>
    
    <div class="row">
        <?php foreach ($this->query->posts() as $post) : ?>
        <div class="col-md-8">
            <h2><a href="<?php $post->thePermalink(); ?>"><?php $post->theTitle(); ?></a></h2>
            <p class="text-muted">Authored by <span class="post-author"><?php $post->theAuthor(); ?></span></p>
            <div class="content">
                <?php $post->theExcerpt(); ?>
            </div>
            <ul class="nav nav-pills">
                <li><a href="<?php $post->theCommentsLink();?>" title="<?php echo htmlspecialchars($post->getTheTitle()); ?>">Comments <span class="badge"><?php echo $post->commentCount; ?></span></a></li>
            </ul>
        </div>
        <?php endforeach; ?>
        <div class="col-md-3 col-md-offset-1 hidden-xs hidden-sm">
            <?php echo $this->partial('sidebar.phtml'); ?>
        </div>
    </div>

<?php endif; // $this->query instanceof \Xend\WordPress\Query\QueryInterface
