<?php 
/* @var $this \Zend_View */ 

if ($this->query instanceof \Xend\WordPress\Query\QueryInterface) : ?>
       
            <h2 id="comments">Comments <span class="badge"><?php echo $this->query->countComments(); ?></span></h2>
            <?php $this->wordpress()->renderCommentList($this->query->comments()); ?>
            <?php if ($this->query->currentPost()->commentStatus == 'open') : ?>
                <?php $this->wordpress()->renderCommentForm(); ?>
            <?php endif; ?>
<?php endif;